//GET http://localhost:3001/api/persons

DELETE https://powerful-fjord-13341.herokuapp.com/api/persons/5d80ac10d3440035ae5babbd
 
 //GET http://localhost:3001/info


 POST http://localhost:3001/api/persons
 Content-Type: application/json

 {
     "name": "AB",
    "number": "321"
 }
 